#!/usr/bin/python

import sys
import string
import codecs
import os
import google

sys.stdout = codecs.lookup('utf-8')[-1](sys.stdout)

argk = 1
argc = len(sys.argv)
query = ' '
while argk < argc:
    query = query + sys.argv[argk] + ' '
    argk = argk+1
data = google.doGoogleSearch(query)

for result in data.results:
    print result.URL 
