#!/usr/bin/python

import sys
import string
import codecs
import os
import google

sys.stdout = codecs.lookup('utf-8')[-1](sys.stdout)

argk = 1
argc = len(sys.argv)
query = sys.stdin.readline()

while query:
#	print query
	data = google.doGoogleSearch(query)
	print "LNK"
	for result in data.results:
		print result.URL 
	print "END"
	query = sys.stdin.readline()
