#!/usr/bin/python

import sys
import string
import codecs
import os
import google

google.LICENSE_KEY = 'gHbcd0RQFHKbR2PQ7o4q/LKfCMVB03Ru'
sys.stdout = codecs.lookup('utf-8')[-1](sys.stdout)

argk = 1
argc = len(sys.argv)
query = sys.stdin.readline()
while query :
	print query
	data = google.doGoogleSearch(query)
	print "BEGIN"
	for result in data.results:
		print result.URL 
	print "END"
	query = sys.stdin.readline()
