#+TITLE:     GNUGOL FAQ
#+AUTHOR:    Dave Täht
#+EMAIL:     d@taht.net
#+DATE:      <2010-12-12 Mon>
#+LANGUAGE:  en
#+TEXT:      Searching the Web in Plain Text
#+OPTIONS:   H:2 num:nil todo:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:nil tags:not-in-toc
#+INFOJS_OPT: view:overview toc:t ltoc:t mouse:underline buttons:0 path:org-info.js
#+STYLE:    <link rel="stylesheet" type="text/css" href="worg.css" />
#+STYLE:    <script type="text/javascript" src="/MathJax/MathJax.js"></script>
#+MATHJAX: align:"left" mathml:nil path:"/MathJax/"
* Why is it called GNUGOL?
  The name came from a 2008, late night discussion/hacking/music session between Michael Taht and Nick Mainsbridge, in his music studio near Sydney, Australia. Mike had been working on a set of concepts designed to push the outer limits of the internet back out to the edges, and was about to give a talk on the subject, so they thrashed it through. 

  While Mike was playing piano, Nick came rushing in with the name. Mike dropped the piano, spent a week locked up in a hotel room writing up what they'd been talking about, gave the talk... then got some proof of concept code over a weekend a few weeks later. Thus - gnugol was born!

  The name is a play on several words - Canoodle, google, gnu, and "New Goal" - which is what designing a custom protocol for client distributed search is all about....

* Where did the idea come from?
  Mike has had a long experience with search engines, having written one in 1996, and another in 1999. 
** Genesis 

   Gnugol began life in 1996 as a shell script that scraped altavista's search results into a format that was compatable with the links text-mode web browser. It went through various incarnations over the years.

** Frustration with "truth in advertising"

   In a meeting with some web advertising executives in 99, I started describing the new IPv13 protocol, which would guarantee that after so many data packets, ADV (advertising) packets had to be sent. Everybody in the room bought it, to my dismay, even a few that shouldn't have been fooled. Soon afterwards he started working on privoxy and other tools like that. 
** A trip to Belize
   where he noticed how slow the internet was in remote locations. 
** Losing an argument with Linus Torvalds 
   about the sha1/gzip ordering in git. 
** ISC.org
   came from a visit to isc.org and some discussions about the efficiency of dns and udp over ipv6. 
** Trips to Nicaragua and Australia 
   Where it was painfully obvious that the internet, especially over lossy 802.11 networks, was often too slow to actually use. Last inputs were the talk, and the name. Mike says "I am a derived work". 
** Latency

When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

* Non surprises
  used a protocol like this internally to assemble their outputs. It's better that protocols like this exist on the edges of the internet, however that may affect others' business models remains to be seen. 
* How does it work? 
  The crux of gnugold is that simple searches easily fit into a single packet, and that establishing short distance http connections on well connected networks is much faster than long distance connections over flaky networks. The simple math for it is something Mike will write up when he gets around to it. 
* How much does it cost? 
  It's currently free. (donations or investors requested). It's my hope that this can become an internet standard for search. There are numerous options for paid search that I'm looking into. One is by dual-licensing the code under the GNU AFFERO public license... another would be for paid secure searching (crypted), and a third option is to wave hands and say that search inevitably must become a commodity. 
* What's it good for?
I see 4 ways in which this tool can be a real win. 
* How can I help? 
  Download the source code. Build it. Contribute. Run a server in a well connected location. Share it. Spread the program around your workplace.
