#+TITLE:     GNUGOLD FAQ
#+AUTHOR:    Dave Täht
#+EMAIL:     d at taht.net
#+DATE:      <2008-08-25 Mo>
#+LANGUAGE:  en
#+TEXT:      Searching the Web over persistent protocols
#+OPTIONS:   H:1 num:nil todo:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:org-info.js
#+LINK_UP: index.html
#+LINK_HOME:
#+STYLE:    <link rel="stylesheet" type="text/css" href="stylesheet.css" />
#+STYLE:    <script type="text/javascript" src="org-info.js"> 
* Why is it called GNUGOLD?
  The name is a play on several words - Canoodle, google, gnu, and "New Goal" - which is what designing a custom protocol for client distributed search is all about...
* What will it do?
  Act as a proxy query router using udp or sctp to more well connected search sites.
* How does it work? 
- Simple searches easily fit into a single packet
- Most responses - when cleared of extra stuff - are less than 16K
- Persistent connections have no setup or teardown time
- DNS lookups done at the center of the internet are fast
- Short distance http connections on well connected networks are much faster than long distance connections over flaky networks. 
* How much does it cost? 
  It's currently free. It's my hope that something like this could become an internet standard for search. There are numerous options for paid search that I'm looking into. 
** Selling rights to the "default" search engine
   Mozilla does this with google
** Dual-licensing the code under the GNU AFFERO public license
** Paid secure searching (crypted)
** Wave hands and say that search inevitably must become a commodity. 
* Use Cases
** Scenario: OLPC - A teacher and 20 students 
A teacher prepares a lesson plan using internet resources and gnugold. In her (well-connected) home, she does her queries using the gnugol plugin, which downloads and keeps organized her data set, collecting the bits of data that she will use to teach the lesson. She then goes to the school for the lesson. Her students, while receiving the lesson, also do queries, many of which the teacher has already asked, and are cached on her laptop, and thus are presented immediately to the kids without the need for external network access.

See also: [[file:trust.org][Trust relationships]].
* How can I help? 
  Download the source code. Build it. Contribute. Run a server in a well connected location. Share it. Spread the program around your workplace.
