#+TITLE:     Index to GNUGOL's doc
#+AUTHOR:    Dave Täht
#+EMAIL:     d at taht.net
#+DATE:      <2010-12-21 Tue>
#+LANGUAGE:  en
#+DESCRIPTION: GNUGOL - an org-mode compatible search client
#+OPTIONS:   H:1 num:nil todo:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:org-info.js
#+LINK_UP:
#+LINK_HOME: 
#+STYLE:    <link rel="stylesheet" type="text/css" href="worg.css" />
#+STYLE:    <script type="text/javascript" src="org-info.js"> 
#+STARTUP: overview hideblocks

